name: Test Workflow

on:
    push:
        branches: [ master-custom ]
    pull_request:
        branches: [ master-custom ]

jobs:
  create-tag:
    runs-on: windows-latest

    steps:
    - name: Exec
      shell: powershell
      run: |
        Get-ItemProperty -Path 'HKLM:\SOFTWARE\Classes\Installer\Dependencies\VC,redist.x86,*' -Name Version